apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
type: Opaque
stringData:
    {{ with .Values.secret -}}
    APP_KEY: {{ .appKey | default "d9iwGCkB7OzSGf7JTY5zjMZgRitC8qed" }}
    DB_ROOT_PSWD: {{ .dbRootPswd | default "toor" }}
    DB_PSWD: {{ .dbPswd | default "toor" }}
    {{- end }}