apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    run: mariadb-service
spec:
  selector:
    app: mariadb-pod
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    app: mariadb-pod
spec:
  containers:
  - name: mariadb
    image: mariadb
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: scrumwala-secret
            key: DB_ROOT_PWSD
      - name: MYSQL_USER
        valueFrom:
          configMapKeyRef:
            name: scrumwala-config
            key: DB_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: scrumwala-secret
            key: DB_PSWD
      - name: MYSQL_DATABASE
        valueFrom:
          configMapKeyRef:
            name: scrumwala-config
            key: DB_NAME
    volumeMounts:
    - name: pvc
      mountPath: /var/lib/mysql
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: mariadb-pv-claim
  restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi