apiVersion: v1
kind: Service
metadata:
  name: scrumwala-service
  labels:
    run: scrumwala-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: scrumwala-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: scrumwala-pod
  labels:
    app: scrumwala-pod
spec:
  containers:
  - name: scrumwala
    image: hussaingandhi/php-5.6-composer
    ports:
    - containerPort: 8081
    env:
      - name: APP_KEY
        value: d9iwGCkB7OzSGf7JTY5zjMZgRitC8qed
      - name: DB_HOST
        value: mariadb-service
      - name: DB_DATABASE
        value: forge
      - name: DB_USERNAME
        value: toor
      - name: DB_PASSWORD
        value: toor
    volumeMounts:
      - name: php-files
        mountPath: /var/www/html
    command: ["/bin/sh", "-c"]
    args: ["php composer.phar update --no-scripts --no-interaction && php composer.phar install --no-scripts --no-interaction && php artisan migrate --force && php artisan serve --host 0.0.0.0 --port 8081"]
  volumes:
    - name: php-files
      hostPath:
        path: /home/hussain.gandhi/personal/kubernetes/Scrumwala
  restartPolicy: Always