apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
data:
  DB_HOST: {{ .Release.Name }}-{{ .Values.global.dbChartName | default "mariadb" }}
  {{ with .Values.config -}}
  DB_NAME: {{ .dbName | default "forge" }}
  DB_USER: {{ .dbUser | default "toor" }}
  {{- end }}